sudo: required
language: java
jdk:
- oraclejdk8
before_cache:
- rm -fr $HOME/.gradle/caches/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script:
  - "./gradlew check"
  - "./gradlew jacocoTestReport"

after_success:
  - "bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'"
  - "./gradlew installDist bootRepackage"
